[tool.black]
line-length = 88
target-version = ['py27','py36','py37']
include = '\.pyi?$'
exclude = '''
(
  /(
     \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | buck-out
    | build
    | dist
    | pai/libs/*
  )/
)
'''